### DISCUSSION TITLE
Dark mode/general theming for Script fields in Tokyo

### DISCUSSION THREAD

**Discussion by VanWeapon** [arnoudkooi/SN-Utils#305] [Ideas]
Tokyo adds dark mode support for lists and forms (finally) however one blindingly missed field type is the script field. 

Would be sweet if we could overwrite the theme of the script editor to a dark theme to match the user's preferences. 

SN uses codemirror script fields, but their documentation only describes how to set themes when pre-rendering them server-side. 
https://codemirror.net/examples/styling/#themes

I was able to do this via using this javascript/css user script injector: [User JavaScript and CSS
](https://chrome.google.com/webstore/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld?hl=en) and setting CSS priority to highest in the options (not sure how this actually translates to the CSS being loaded) 

This only works when popped in to frame, i.e. no navigator

Modified CSS stylesheet i used:

```css
/*

    Name:       Dracula
    Author:     Michael Kaminsky (http://github.com/mkaminsky11)

    Original dracula color scheme by Zeno Rocha (https://github.com/zenorocha/dracula-theme)

*/


.cm-s-snc.CodeMirror, .cm-s-snc .CodeMirror-gutters {
  background-color: #282a36 !important;
  color: #f8f8f2 !important;
  border: none;
}
.cm-s-snc .CodeMirror-gutters { color: #282a36;  !important}
.cm-s-snc .CodeMirror-cursor { border-left: solid thin #f8f8f0; !important }
.cm-s-snc .CodeMirror-linenumber { color: #6D8A88; !important }
.cm-s-snc .CodeMirror-selected { background: rgba(255, 255, 255, 0.10);  !important}
.cm-s-snc .CodeMirror-line::selection, .cm-s-snc .CodeMirror-line > span::selection, .cm-s-snc .CodeMirror-line > span > span::selection { background: rgba(255, 255, 255, 0.10);  !important}
.cm-s-snc .CodeMirror-line::-moz-selection, .cm-s-snc .CodeMirror-line > span::-moz-selection, .cm-s-snc .CodeMirror-line > span > span::-moz-selection { background: rgba(255, 255, 255, 0.10);  !important}
.cm-s-snc span.cm-comment { color: #6272a4;  !important}
.cm-s-snc span.cm-string, .cm-s-snc span.cm-string-2 { color: #f1fa8c;  !important}
.cm-s-snc span.cm-number { color: #bd93f9; !important }
.cm-s-snc span.cm-variable { color: #50fa7b; !important }
.cm-s-snc span.cm-variable-2 { color: white;  !important}
.cm-s-snc span.cm-def { color: #50fa7b;  !important}
.cm-s-snc span.cm-operator { color: #ff79c6;  !important}
.cm-s-snc span.cm-keyword { color: #ff79c6; !important }
.cm-s-snc span.cm-atom { color: #bd93f9; !important }
.cm-s-snc span.cm-meta { color: #f8f8f2;  !important}
.cm-s-snc span.cm-tag { color: #ff79c6;  !important}
.cm-s-snc span.cm-attribute { color: #50fa7b;  !important}
.cm-s-snc span.cm-qualifier { color: #50fa7b; !important }
.cm-s-snc span.cm-property { color: #66d9ef;  !important}
.cm-s-snc span.cm-builtin { color: #50fa7b;  !important}
.cm-s-snc span.cm-variable-3, .cm-s-snc span.cm-type { color: #ffb86c;  !important}

.cm-s-snc .CodeMirror-activeline-background { background: rgba(255,255,255,0.1);  !important}
.cm-s-snc .CodeMirror-matchingbracket { text-decoration: underline; color: white !important; }
```

Resulting
![image](https://user-images.githubusercontent.com/30616047/191152166-2ce0257a-1301-457b-becf-2bec83d9da7f.png)
